# 
#  .bashrc
#  back-to-bash
# 

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# ==========
# = Config =
# ==========

EDITOR='mvim --nofork'
export EDITOR

# Use English as the language
LANG='en_US.UTF-8'
LC_CTYPE='en_US.UTF-8'
export LANG
export LC_CTYPE

PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"'
export PROMPT_COMMAND

PATH=/usr/local/Cellar/ruby/1.9.2-p0/bin:/usr/local/sbin:/usr/local/bin:/usr/local/share/npm/bin:$PATH
export PATH

NODE_PATH=/usr/local/lib/node
export NODE_PATH

MAN_PATH=$MAN_PATH:/usr/local/Cellar/node/0.2.1/share/man
export MAN_PATH

force_color_prompt="Y"

#####

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
  if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
    # We have color support; assume it's compliant with Ecma-48
    # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
    # a case would tend to support setf rather than setaf.)
    color_prompt=yes
  else
    color_prompt=
  fi
fi

if [ "$color_prompt" = yes ]; then
  PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
  PS1='\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# ===========
# = Aliases =
# ===========

# some more ls aliases
alias ls='ls -G'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Reload bash (rebash)
alias rebash='source $HOME/.bashrc'

# Start screensaver
alias ss="osascript -e 'tell application id \"com.apple.ScreenSaver.Engine\" to launch'"

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# ==============
# = Completion =
# ==============

if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

if [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
fi

# ==========
# = Others =
# ==========

set -o vi
